# Generated by Django 4.1 on 2022-10-14 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("demo", "0003_alter_bankpayment_bank_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="bankpayment",
            old_name="bank",
            new_name="bank_name",
        ),
        migrations.AlterField(
            model_name="promptpaypayment",
            name="phone_number",
            field=models.CharField(max_length=10),
        ),
    ]
